CREATE TABLE "XCC_CHECKPOINT" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CUENTA" uuid,
	"FECHA" timestamp with time zone,
	"SALDO_CAPITAL" double precision,
	"SALDO_INTERES" double precision,
	"OBSERVACIONES" text,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid
);
--> statement-breakpoint
CREATE TABLE "XCC_CLIENTES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CLIENTE" uuid,
	"ID_CONDICION_IMPOSITIVA" uuid
);
--> statement-breakpoint
CREATE TABLE "XCC_CLIENTES_CONDICION_HISTORICO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CLIENTE" uuid,
	"ID_CONDICION_IMPOSITIVA" uuid,
	"VIGENTE_DESDE" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "XCC_CONDICIONES_IMPOSITIVAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"ALICUOTA_GANANCIAS" double precision
);
--> statement-breakpoint
CREATE TABLE "XCC_CUENTAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CUENTA" uuid,
	"TASA_INTERES" double precision,
	"SALDO_MIN_INTERES" double precision,
	"GASTO_MENSUAL" double precision,
	"SALDO_MIN_GASTO_MENSUAL" double precision
);
--> statement-breakpoint
CREATE TABLE "XCC_CUENTAS_TASA_HISTORICO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CUENTA" uuid,
	"TASA" double precision,
	"VIGENTE_DESDE" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "XCC_MOVIMIENTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CUENTA" uuid,
	"ID_TIPO_MOVIMIENTO" uuid,
	"FECHA" timestamp with time zone,
	"MONTO" double precision,
	"OBSERVACIONES" text,
	"NRO_RECIBO" text,
	"ID_TRAMITE" uuid,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid
);
--> statement-breakpoint
CREATE TABLE "XCC_PRODUCTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PRODUCTO" uuid,
	"TASA_INTERES" double precision,
	"SALDO_MIN_INTERES" double precision,
	"GASTO_MENSUAL" double precision,
	"SALDO_MIN_GASTO_MENSUAL" double precision
);
--> statement-breakpoint
CREATE TABLE "XCC_SALDOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CUENTA" uuid,
	"FECHA" timestamp with time zone,
	"ID_TIPO_MOVIMIENTO" uuid NOT NULL,
	"ID_XCC_MOVIMIENTO" uuid,
	"CONCEPTO" text,
	"MONTO" double precision,
	"SALDO_CAPITAL" double precision,
	"SALDO_INTERES" double precision,
	"TASA_APLICADA" double precision
);
--> statement-breakpoint
CREATE TABLE "XCC_TIPOS_MOVIMIENTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"SIGNO" integer,
	"AFECTA_CAPITAL" boolean,
	"AFECTA_INTERES" boolean,
	"ES_DEVENGAMIENTO" boolean,
	"ES_ACREDITACION_INTERES" boolean,
	"ORDEN" integer,
	"GENERADO_POR_MOTOR" boolean
);
--> statement-breakpoint
CREATE TABLE "XCC_TIPOS_RETENCION" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"ORDEN" integer,
	"ACTIVA" boolean,
	"ALICUOTA" double precision
);
--> statement-breakpoint
ALTER TABLE "XCC_CHECKPOINT" ADD CONSTRAINT "XCC_CHECKPOINT_ID_CUENTA_CUENTAS_ID_fk" FOREIGN KEY ("ID_CUENTA") REFERENCES "public"."CUENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CHECKPOINT" ADD CONSTRAINT "XCC_CHECKPOINT_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CLIENTES" ADD CONSTRAINT "XCC_CLIENTES_ID_CLIENTE_CLIENTES_ID_fk" FOREIGN KEY ("ID_CLIENTE") REFERENCES "public"."CLIENTES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CLIENTES" ADD CONSTRAINT "XCC_CLIENTES_ID_CONDICION_IMPOSITIVA_XCC_CONDICIONES_IMPOSITIVAS_ID_fk" FOREIGN KEY ("ID_CONDICION_IMPOSITIVA") REFERENCES "public"."XCC_CONDICIONES_IMPOSITIVAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CLIENTES_CONDICION_HISTORICO" ADD CONSTRAINT "XCC_CLIENTES_CONDICION_HISTORICO_ID_CLIENTE_CLIENTES_ID_fk" FOREIGN KEY ("ID_CLIENTE") REFERENCES "public"."CLIENTES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CLIENTES_CONDICION_HISTORICO" ADD CONSTRAINT "XCC_CLIENTES_CONDICION_HISTORICO_ID_CONDICION_IMPOSITIVA_XCC_CONDICIONES_IMPOSITIVAS_ID_fk" FOREIGN KEY ("ID_CONDICION_IMPOSITIVA") REFERENCES "public"."XCC_CONDICIONES_IMPOSITIVAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CUENTAS" ADD CONSTRAINT "XCC_CUENTAS_ID_CUENTA_CUENTAS_ID_fk" FOREIGN KEY ("ID_CUENTA") REFERENCES "public"."CUENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CUENTAS_TASA_HISTORICO" ADD CONSTRAINT "XCC_CUENTAS_TASA_HISTORICO_ID_CUENTA_CUENTAS_ID_fk" FOREIGN KEY ("ID_CUENTA") REFERENCES "public"."CUENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_MOVIMIENTOS" ADD CONSTRAINT "XCC_MOVIMIENTOS_ID_CUENTA_CUENTAS_ID_fk" FOREIGN KEY ("ID_CUENTA") REFERENCES "public"."CUENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_MOVIMIENTOS" ADD CONSTRAINT "XCC_MOVIMIENTOS_ID_TIPO_MOVIMIENTO_XCC_TIPOS_MOVIMIENTOS_ID_fk" FOREIGN KEY ("ID_TIPO_MOVIMIENTO") REFERENCES "public"."XCC_TIPOS_MOVIMIENTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_MOVIMIENTOS" ADD CONSTRAINT "XCC_MOVIMIENTOS_ID_TRAMITE_TRAMITES_ID_fk" FOREIGN KEY ("ID_TRAMITE") REFERENCES "public"."TRAMITES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_MOVIMIENTOS" ADD CONSTRAINT "XCC_MOVIMIENTOS_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_PRODUCTOS" ADD CONSTRAINT "XCC_PRODUCTOS_ID_PRODUCTO_PRODUCTOS_ID_fk" FOREIGN KEY ("ID_PRODUCTO") REFERENCES "public"."PRODUCTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_SALDOS" ADD CONSTRAINT "XCC_SALDOS_ID_CUENTA_CUENTAS_ID_fk" FOREIGN KEY ("ID_CUENTA") REFERENCES "public"."CUENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_SALDOS" ADD CONSTRAINT "XCC_SALDOS_ID_TIPO_MOVIMIENTO_XCC_TIPOS_MOVIMIENTOS_ID_fk" FOREIGN KEY ("ID_TIPO_MOVIMIENTO") REFERENCES "public"."XCC_TIPOS_MOVIMIENTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_SALDOS" ADD CONSTRAINT "XCC_SALDOS_ID_XCC_MOVIMIENTO_XCC_MOVIMIENTOS_ID_fk" FOREIGN KEY ("ID_XCC_MOVIMIENTO") REFERENCES "public"."XCC_MOVIMIENTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "XCC_CLIENTES_ID_CLIENTE_UNIQUE" ON "XCC_CLIENTES" USING btree ("ID_CLIENTE");--> statement-breakpoint
CREATE UNIQUE INDEX "XCC_CUENTAS_ID_CUENTA_UNIQUE" ON "XCC_CUENTAS" USING btree ("ID_CUENTA");--> statement-breakpoint
CREATE UNIQUE INDEX "XCC_PRODUCTOS_ID_PRODUCTO_UNIQUE" ON "XCC_PRODUCTOS" USING btree ("ID_PRODUCTO");