ALTER TABLE "XCC_MOVIMIENTOS" ALTER COLUMN "ALTA_FECHA" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "XCC_CLIENTES_CONDICION_HISTORICO" ADD COLUMN "ALTA_FECHA" timestamp with time zone DEFAULT now();--> statement-breakpoint
ALTER TABLE "XCC_CUENTAS_TASA_HISTORICO" ADD COLUMN "ALTA_FECHA" timestamp with time zone DEFAULT now();