CREATE UNIQUE INDEX "XCC_CONDICIONES_IMPOSITIVAS_CODIGO_UNIQUE" ON "XCC_CONDICIONES_IMPOSITIVAS" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "XCC_TIPOS_MOVIMIENTOS_CODIGO_UNIQUE" ON "XCC_TIPOS_MOVIMIENTOS" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "XCC_TIPOS_RETENCION_CODIGO_UNIQUE" ON "XCC_TIPOS_RETENCION" USING btree ("CODIGO");