CREATE TABLE "XCC_CONDICIONES_RETENCION" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_CONDICION_IMPOSITIVA" uuid NOT NULL,
	"ID_TIPO_RETENCION" uuid NOT NULL,
	"ALICUOTA" double precision NOT NULL
);
--> statement-breakpoint
ALTER TABLE "XCC_CONDICIONES_RETENCION" ADD CONSTRAINT "XCC_CONDICIONES_RETENCION_ID_CONDICION_IMPOSITIVA_XCC_CONDICIONES_IMPOSITIVAS_ID_fk" FOREIGN KEY ("ID_CONDICION_IMPOSITIVA") REFERENCES "public"."XCC_CONDICIONES_IMPOSITIVAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "XCC_CONDICIONES_RETENCION" ADD CONSTRAINT "XCC_CONDICIONES_RETENCION_ID_TIPO_RETENCION_XCC_TIPOS_RETENCION_ID_fk" FOREIGN KEY ("ID_TIPO_RETENCION") REFERENCES "public"."XCC_TIPOS_RETENCION"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "XCC_CONDICIONES_RETENCION_CONDICION_RETENCION_UNIQUE" ON "XCC_CONDICIONES_RETENCION" USING btree ("ID_CONDICION_IMPOSITIVA","ID_TIPO_RETENCION");