CREATE UNIQUE INDEX "INTERFACES_MENUES_INTERFAZ_MENU_UNIQUE" ON "INTERFACES_MENUES" USING btree ("ID_INTERFAZ","ID_MENU");--> statement-breakpoint
CREATE UNIQUE INDEX "PERMISOS_PERFIL_HERRAMIENTA_UNIQUE" ON "PERMISOS" USING btree ("ID_PERFIL","ID_HERRAMIENTA");--> statement-breakpoint
ALTER TABLE "PERMISOS" DROP COLUMN "VER";