CREATE TABLE "ACCIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ESTRATEGIA" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"COMANDO" text,
	"COMODIN" jsonb
);
--> statement-breakpoint
CREATE TABLE "CARACTERES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "CLIENTES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_LEGAJO" uuid,
	"ID_CARACTER" uuid,
	"ES_TITULAR" boolean,
	"ID_TIPO_DOCUMENTO" uuid,
	"NRO_DOCUMENTO" text,
	"APELLIDO" text,
	"NOMBRE" text NOT NULL,
	"ID_GENERO" uuid,
	"ID_PROVINCIA" uuid,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid,
	"AUDIT_FECHA" timestamp with time zone,
	"AUDIT_USUARIO" uuid
);
--> statement-breakpoint
CREATE TABLE "ENTIDADES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ESTADOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ESTRATEGIA" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"ES_INICIAL" boolean,
	"ES_FINAL" boolean,
	"COMODIN" jsonb
);
--> statement-breakpoint
CREATE TABLE "ESTIMULOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ESTRATEGIA" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"COMODIN" jsonb
);
--> statement-breakpoint
CREATE TABLE "ESTRATEGIAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"ID_ENTIDAD" uuid
);
--> statement-breakpoint
CREATE TABLE "GENEROS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HISTORIAL" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_TRANSICION" uuid,
	"ID_ENTIDAD" uuid,
	"ID_RELACION" uuid,
	"OBSERVACION" text,
	"ACCIONES_STATUS" integer,
	"ACCIONES_ERROR" text,
	"AUDIT_FECHA" timestamp with time zone,
	"AUDIT_USUARIO" uuid
);
--> statement-breakpoint
CREATE TABLE "LEGAJOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"NUMERO" text NOT NULL,
	"ID_ESTADO" uuid,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid,
	"AUDIT_FECHA" timestamp with time zone,
	"AUDIT_USUARIO" uuid,
	"COMODIN" jsonb
);
--> statement-breakpoint
CREATE TABLE "PAISES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PROVINCIAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PAIS" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TIPOS_DOCUMENTO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TRANSICIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ESTRATEGIA" uuid,
	"ID_ESTADO_0" uuid,
	"ID_ESTIMULO" uuid,
	"ID_ESTADO_1" uuid
);
--> statement-breakpoint
CREATE TABLE "TRANSICIONES_ACCIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_TRANSICION" uuid,
	"ID_ACCION" uuid,
	"ORDEN" integer
);
--> statement-breakpoint
ALTER TABLE "ACCIONES" ADD CONSTRAINT "ACCIONES_ID_ESTRATEGIA_ESTRATEGIAS_ID_fk" FOREIGN KEY ("ID_ESTRATEGIA") REFERENCES "public"."ESTRATEGIAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_LEGAJO_LEGAJOS_ID_fk" FOREIGN KEY ("ID_LEGAJO") REFERENCES "public"."LEGAJOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_CARACTER_CARACTERES_ID_fk" FOREIGN KEY ("ID_CARACTER") REFERENCES "public"."CARACTERES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_TIPO_DOCUMENTO_TIPOS_DOCUMENTO_ID_fk" FOREIGN KEY ("ID_TIPO_DOCUMENTO") REFERENCES "public"."TIPOS_DOCUMENTO"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_GENERO_GENEROS_ID_fk" FOREIGN KEY ("ID_GENERO") REFERENCES "public"."GENEROS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_PROVINCIA_PROVINCIAS_ID_fk" FOREIGN KEY ("ID_PROVINCIA") REFERENCES "public"."PROVINCIAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_AUDIT_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("AUDIT_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ESTADOS" ADD CONSTRAINT "ESTADOS_ID_ESTRATEGIA_ESTRATEGIAS_ID_fk" FOREIGN KEY ("ID_ESTRATEGIA") REFERENCES "public"."ESTRATEGIAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ESTIMULOS" ADD CONSTRAINT "ESTIMULOS_ID_ESTRATEGIA_ESTRATEGIAS_ID_fk" FOREIGN KEY ("ID_ESTRATEGIA") REFERENCES "public"."ESTRATEGIAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ESTRATEGIAS" ADD CONSTRAINT "ESTRATEGIAS_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD CONSTRAINT "HISTORIAL_ID_TRANSICION_TRANSICIONES_ID_fk" FOREIGN KEY ("ID_TRANSICION") REFERENCES "public"."TRANSICIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD CONSTRAINT "HISTORIAL_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD CONSTRAINT "HISTORIAL_AUDIT_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("AUDIT_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LEGAJOS" ADD CONSTRAINT "LEGAJOS_ID_ESTADO_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LEGAJOS" ADD CONSTRAINT "LEGAJOS_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LEGAJOS" ADD CONSTRAINT "LEGAJOS_AUDIT_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("AUDIT_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROVINCIAS" ADD CONSTRAINT "PROVINCIAS_ID_PAIS_PAISES_ID_fk" FOREIGN KEY ("ID_PAIS") REFERENCES "public"."PAISES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRANSICIONES" ADD CONSTRAINT "TRANSICIONES_ID_ESTRATEGIA_ESTRATEGIAS_ID_fk" FOREIGN KEY ("ID_ESTRATEGIA") REFERENCES "public"."ESTRATEGIAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRANSICIONES" ADD CONSTRAINT "TRANSICIONES_ID_ESTADO_0_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO_0") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRANSICIONES" ADD CONSTRAINT "TRANSICIONES_ID_ESTIMULO_ESTIMULOS_ID_fk" FOREIGN KEY ("ID_ESTIMULO") REFERENCES "public"."ESTIMULOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRANSICIONES" ADD CONSTRAINT "TRANSICIONES_ID_ESTADO_1_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO_1") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRANSICIONES_ACCIONES" ADD CONSTRAINT "TRANSICIONES_ACCIONES_ID_TRANSICION_TRANSICIONES_ID_fk" FOREIGN KEY ("ID_TRANSICION") REFERENCES "public"."TRANSICIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRANSICIONES_ACCIONES" ADD CONSTRAINT "TRANSICIONES_ACCIONES_ID_ACCION_ACCIONES_ID_fk" FOREIGN KEY ("ID_ACCION") REFERENCES "public"."ACCIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ESTADOS_ESTRATEGIA_INICIAL_UNIQUE" ON "ESTADOS" USING btree ("ID_ESTRATEGIA") WHERE "ESTADOS"."ES_INICIAL" = true;--> statement-breakpoint
CREATE UNIQUE INDEX "TRANSICIONES_ESTRATEGIA_ESTADO0_ESTIMULO_UNIQUE" ON "TRANSICIONES" USING btree ("ID_ESTRATEGIA","ID_ESTADO_0","ID_ESTIMULO");