CREATE TABLE "BANDEJAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"QUERY" text,
	"COLUMNAS" jsonb
);
--> statement-breakpoint
CREATE TABLE "BANDEJAS_FILTROS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_BANDEJA" uuid,
	"ID_FILTRO" uuid,
	"CAMPO" text,
	"ORDEN" integer
);
--> statement-breakpoint
CREATE TABLE "BANDEJAS_PERFILES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_BANDEJA" uuid,
	"ID_PERFIL" uuid
);
--> statement-breakpoint
CREATE TABLE "FILTROS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"TIPO" text,
	"QUERY" text
);
--> statement-breakpoint
ALTER TABLE "BANDEJAS_FILTROS" ADD CONSTRAINT "BANDEJAS_FILTROS_ID_BANDEJA_BANDEJAS_ID_fk" FOREIGN KEY ("ID_BANDEJA") REFERENCES "public"."BANDEJAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "BANDEJAS_FILTROS" ADD CONSTRAINT "BANDEJAS_FILTROS_ID_FILTRO_FILTROS_ID_fk" FOREIGN KEY ("ID_FILTRO") REFERENCES "public"."FILTROS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "BANDEJAS_PERFILES" ADD CONSTRAINT "BANDEJAS_PERFILES_ID_BANDEJA_BANDEJAS_ID_fk" FOREIGN KEY ("ID_BANDEJA") REFERENCES "public"."BANDEJAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "BANDEJAS_PERFILES" ADD CONSTRAINT "BANDEJAS_PERFILES_ID_PERFIL_PERFILES_ID_fk" FOREIGN KEY ("ID_PERFIL") REFERENCES "public"."PERFILES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "BANDEJAS_PERFILES_BANDEJA_PERFIL_UNIQUE" ON "BANDEJAS_PERFILES" USING btree ("ID_BANDEJA","ID_PERFIL");