CREATE TABLE "LAYOUTS_LEGAJO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "LAYOUTS_LEGAJO_BANDEJAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_BANDEJA" uuid,
	"ID_LAYOUT" uuid
);
--> statement-breakpoint
CREATE TABLE "LAYOUTS_LEGAJO_SOLAPAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_LAYOUT" uuid,
	"ORDEN" integer,
	"NOMBRE" text NOT NULL,
	"ID_HERRAMIENTA" uuid,
	"VISIBLE" boolean
);
--> statement-breakpoint
ALTER TABLE "LAYOUTS_LEGAJO_BANDEJAS" ADD CONSTRAINT "LAYOUTS_LEGAJO_BANDEJAS_ID_BANDEJA_BANDEJAS_ID_fk" FOREIGN KEY ("ID_BANDEJA") REFERENCES "public"."BANDEJAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LAYOUTS_LEGAJO_BANDEJAS" ADD CONSTRAINT "LAYOUTS_LEGAJO_BANDEJAS_ID_LAYOUT_LAYOUTS_LEGAJO_ID_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES "public"."LAYOUTS_LEGAJO"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LAYOUTS_LEGAJO_SOLAPAS" ADD CONSTRAINT "LAYOUTS_LEGAJO_SOLAPAS_ID_LAYOUT_LAYOUTS_LEGAJO_ID_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES "public"."LAYOUTS_LEGAJO"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LAYOUTS_LEGAJO_SOLAPAS" ADD CONSTRAINT "LAYOUTS_LEGAJO_SOLAPAS_ID_HERRAMIENTA_HERRAMIENTAS_ID_fk" FOREIGN KEY ("ID_HERRAMIENTA") REFERENCES "public"."HERRAMIENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "LAYOUTS_LEGAJO_BANDEJAS_BANDEJA_UNIQUE" ON "LAYOUTS_LEGAJO_BANDEJAS" USING btree ("ID_BANDEJA");--> statement-breakpoint
CREATE UNIQUE INDEX "LAYOUTS_LEGAJO_SOLAPAS_LAYOUT_ORDEN_UNIQUE" ON "LAYOUTS_LEGAJO_SOLAPAS" USING btree ("ID_LAYOUT","ORDEN");