ALTER TABLE "LAYOUTS_LEGAJO_BANDEJAS" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "LAYOUTS_LEGAJO_BANDEJAS" CASCADE;--> statement-breakpoint
ALTER TABLE "BANDEJAS" ADD COLUMN "ID_LAYOUT" uuid;--> statement-breakpoint
ALTER TABLE "BANDEJAS" ADD CONSTRAINT "BANDEJAS_ID_LAYOUT_LAYOUTS_LEGAJO_ID_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES "public"."LAYOUTS_LEGAJO"("ID") ON DELETE no action ON UPDATE no action;