CREATE TABLE "PERFILES_ESTIMULOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PERFIL" uuid,
	"ID_ESTIMULO" uuid
);
--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD COLUMN "ID_ESTADO_0" uuid;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD COLUMN "ID_ESTIMULO" uuid;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD COLUMN "ID_ESTADO_1" uuid;--> statement-breakpoint
ALTER TABLE "PERFILES_ESTIMULOS" ADD CONSTRAINT "PERFILES_ESTIMULOS_ID_PERFIL_PERFILES_ID_fk" FOREIGN KEY ("ID_PERFIL") REFERENCES "public"."PERFILES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PERFILES_ESTIMULOS" ADD CONSTRAINT "PERFILES_ESTIMULOS_ID_ESTIMULO_ESTIMULOS_ID_fk" FOREIGN KEY ("ID_ESTIMULO") REFERENCES "public"."ESTIMULOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "PERFILES_ESTIMULOS_PERFIL_ESTIMULO_UNIQUE" ON "PERFILES_ESTIMULOS" USING btree ("ID_PERFIL","ID_ESTIMULO");--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD CONSTRAINT "HISTORIAL_ID_ESTADO_0_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO_0") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD CONSTRAINT "HISTORIAL_ID_ESTIMULO_ESTIMULOS_ID_fk" FOREIGN KEY ("ID_ESTIMULO") REFERENCES "public"."ESTIMULOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HISTORIAL" ADD CONSTRAINT "HISTORIAL_ID_ESTADO_1_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO_1") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;