CREATE TABLE "CATEGORIAS_TIPOS_TRAMITE" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "CUENTAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_LEGAJO" uuid,
	"NUMERO" text NOT NULL,
	"ID_PRODUCTO" uuid,
	"ID_ESTADO" uuid,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid,
	"AUDIT_FECHA" timestamp with time zone,
	"AUDIT_USUARIO" uuid,
	"COMODIN" jsonb
);
--> statement-breakpoint
CREATE TABLE "TIPOS_CAMPOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TIPOS_TRAMITE" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"COMODIN" jsonb,
	"ID_CATEGORIA" uuid,
	"ID_ESTRATEGIA" uuid,
	"ID_ENTIDAD" uuid,
	"FILTRO" text,
	"COMPONENTE" text
);
--> statement-breakpoint
CREATE TABLE "TIPOS_TRAMITE_CAMPOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"ID_TIPO_TRAMITE" uuid,
	"ID_TIPO_CAMPO" uuid,
	"ORDEN" integer,
	"OBLIGATORIO" boolean,
	"VISIBLE" boolean,
	"EDITABLE" boolean,
	"LONGITUD_MAX" integer,
	"NUM_MIN" integer,
	"NUM_MAX" integer,
	"NUM_STEP" integer,
	"RADIO_GROUP" integer,
	"PLACEHOLDER" text,
	"AYUDA" text,
	"MASCARA" text,
	"REGEX" text,
	"LISTA_VALORES" text
);
--> statement-breakpoint
CREATE TABLE "TRAMITES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_TIPO_TRAMITE" uuid,
	"ID_ESTADO" uuid,
	"ID_REGISTRO" uuid,
	"COMODIN" jsonb,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid,
	"AUDIT_FECHA" timestamp with time zone,
	"AUDIT_USUARIO" uuid,
	"ID_TRAMITE_PADRE" uuid
);
--> statement-breakpoint
CREATE TABLE "TRAMITES_CAMPOS_DATOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_TRAMITE" uuid,
	"ID_TIPO_TRAMITE_CAMPO" uuid,
	"VALOR_TEXTO" text,
	"VALOR_NUMERO" integer,
	"VALOR_FECHA" timestamp with time zone,
	"VALOR_BOOLEANO" boolean,
	"ID_ARCHIVO_ADJUNTO" uuid
);
--> statement-breakpoint
ALTER TABLE "BANDEJAS" ADD COLUMN "TIPO_APERTURA" text;--> statement-breakpoint
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_ID_LEGAJO_LEGAJOS_ID_fk" FOREIGN KEY ("ID_LEGAJO") REFERENCES "public"."LEGAJOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_ID_PRODUCTO_PRODUCTOS_ID_fk" FOREIGN KEY ("ID_PRODUCTO") REFERENCES "public"."PRODUCTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_ID_ESTADO_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_AUDIT_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("AUDIT_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE" ADD CONSTRAINT "TIPOS_TRAMITE_ID_CATEGORIA_CATEGORIAS_TIPOS_TRAMITE_ID_fk" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "public"."CATEGORIAS_TIPOS_TRAMITE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE" ADD CONSTRAINT "TIPOS_TRAMITE_ID_ESTRATEGIA_ESTRATEGIAS_ID_fk" FOREIGN KEY ("ID_ESTRATEGIA") REFERENCES "public"."ESTRATEGIAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE" ADD CONSTRAINT "TIPOS_TRAMITE_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE_CAMPOS" ADD CONSTRAINT "TIPOS_TRAMITE_CAMPOS_ID_TIPO_TRAMITE_TIPOS_TRAMITE_ID_fk" FOREIGN KEY ("ID_TIPO_TRAMITE") REFERENCES "public"."TIPOS_TRAMITE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE_CAMPOS" ADD CONSTRAINT "TIPOS_TRAMITE_CAMPOS_ID_TIPO_CAMPO_TIPOS_CAMPOS_ID_fk" FOREIGN KEY ("ID_TIPO_CAMPO") REFERENCES "public"."TIPOS_CAMPOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_ID_TIPO_TRAMITE_TIPOS_TRAMITE_ID_fk" FOREIGN KEY ("ID_TIPO_TRAMITE") REFERENCES "public"."TIPOS_TRAMITE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_ID_ESTADO_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_AUDIT_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("AUDIT_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_ID_TRAMITE_PADRE_TRAMITES_ID_fk" FOREIGN KEY ("ID_TRAMITE_PADRE") REFERENCES "public"."TRAMITES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES_CAMPOS_DATOS" ADD CONSTRAINT "TRAMITES_CAMPOS_DATOS_ID_TRAMITE_TRAMITES_ID_fk" FOREIGN KEY ("ID_TRAMITE") REFERENCES "public"."TRAMITES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES_CAMPOS_DATOS" ADD CONSTRAINT "TRAMITES_CAMPOS_DATOS_ID_TIPO_TRAMITE_CAMPO_TIPOS_TRAMITE_CAMPOS_ID_fk" FOREIGN KEY ("ID_TIPO_TRAMITE_CAMPO") REFERENCES "public"."TIPOS_TRAMITE_CAMPOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "TRAMITES_CAMPOS_DATOS_TRAMITE_CAMPO_UNIQUE" ON "TRAMITES_CAMPOS_DATOS" USING btree ("ID_TRAMITE","ID_TIPO_TRAMITE_CAMPO");