CREATE TABLE "ARCHIVOS_ADJUNTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ENTIDAD" uuid,
	"ID_REGISTRO" uuid,
	"ID_TIPO_ARCHIVO_ADJUNTO" uuid,
	"NOMBRE_ORIGINAL" text,
	"RUTA_ARCHIVO" text,
	"TAMANIO_BYTES" integer,
	"ALTA_FECHA" timestamp with time zone,
	"ALTA_USUARIO" uuid,
	"AUDIT_FECHA" timestamp with time zone,
	"AUDIT_USUARIO" uuid
);
--> statement-breakpoint
CREATE TABLE "TIPOS_ARCHIVOS_ADJUNTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"EXTENSION" text,
	"MIMETYPE" text,
	"PERMITE_CARGA" boolean,
	"PERMITE_DOWNLOAD" boolean,
	"RENDERIZAR" boolean
);
--> statement-breakpoint
ALTER TABLE "USUARIOS" ADD COLUMN "ID_ARCHIVO_ADJUNTO" uuid;--> statement-breakpoint
ALTER TABLE "ARCHIVOS_ADJUNTOS" ADD CONSTRAINT "ARCHIVOS_ADJUNTOS_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ARCHIVOS_ADJUNTOS" ADD CONSTRAINT "ARCHIVOS_ADJUNTOS_ID_TIPO_ARCHIVO_ADJUNTO_TIPOS_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_TIPO_ARCHIVO_ADJUNTO") REFERENCES "public"."TIPOS_ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ARCHIVOS_ADJUNTOS" ADD CONSTRAINT "ARCHIVOS_ADJUNTOS_ALTA_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("ALTA_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ARCHIVOS_ADJUNTOS" ADD CONSTRAINT "ARCHIVOS_ADJUNTOS_AUDIT_USUARIO_USUARIOS_ID_fk" FOREIGN KEY ("AUDIT_USUARIO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TRAMITES_CAMPOS_DATOS" ADD CONSTRAINT "TRAMITES_CAMPOS_DATOS_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;