CREATE TABLE "GENERACIONES_DOCUMENTO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_MODELO" uuid,
	"ID_ENTIDAD" uuid,
	"ID_REGISTRO" uuid,
	"DATOS" jsonb,
	"ESTADO" text,
	"ID_ARCHIVO_RESULTADO" uuid,
	"ERROR" text,
	"ALTA_FECHA" timestamp with time zone,
	"AUDIT_FECHA" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "MODELOS_ADJUNTO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ARCHIVO_ADJUNTO" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"DESCRIPCION" text
);
--> statement-breakpoint
CREATE TABLE "PLACEHOLDERS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"QUERY" text,
	"ESCAPAR" boolean,
	"COMODIN" jsonb
);
--> statement-breakpoint
ALTER TABLE "GENERACIONES_DOCUMENTO" ADD CONSTRAINT "GENERACIONES_DOCUMENTO_ID_MODELO_MODELOS_ADJUNTO_ID_fk" FOREIGN KEY ("ID_MODELO") REFERENCES "public"."MODELOS_ADJUNTO"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GENERACIONES_DOCUMENTO" ADD CONSTRAINT "GENERACIONES_DOCUMENTO_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GENERACIONES_DOCUMENTO" ADD CONSTRAINT "GENERACIONES_DOCUMENTO_ID_ARCHIVO_RESULTADO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_RESULTADO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MODELOS_ADJUNTO" ADD CONSTRAINT "MODELOS_ADJUNTO_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "MODELOS_ADJUNTO_CODIGO_UNIQUE" ON "MODELOS_ADJUNTO" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "MODELOS_ADJUNTO_ARCHIVO_UNIQUE" ON "MODELOS_ADJUNTO" USING btree ("ID_ARCHIVO_ADJUNTO");--> statement-breakpoint
CREATE UNIQUE INDEX "PLACEHOLDERS_CODIGO_UNIQUE" ON "PLACEHOLDERS" USING btree ("CODIGO");