CREATE TABLE "PLANTILLAS_ADJUNTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ARCHIVO_ADJUNTO" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"DESCRIPCION" text
);
--> statement-breakpoint
ALTER TABLE "GENERACIONES_DOCUMENTO" ADD COLUMN "ID_PLANTILLA" uuid;--> statement-breakpoint
ALTER TABLE "PLANTILLAS_ADJUNTOS" ADD CONSTRAINT "PLANTILLAS_ADJUNTOS_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "PLANTILLAS_ADJUNTOS_CODIGO_UNIQUE" ON "PLANTILLAS_ADJUNTOS" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "PLANTILLAS_ADJUNTOS_ARCHIVO_UNIQUE" ON "PLANTILLAS_ADJUNTOS" USING btree ("ID_ARCHIVO_ADJUNTO");--> statement-breakpoint
ALTER TABLE "GENERACIONES_DOCUMENTO" ADD CONSTRAINT "GENERACIONES_DOCUMENTO_ID_PLANTILLA_PLANTILLAS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_PLANTILLA") REFERENCES "public"."PLANTILLAS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;