ALTER TABLE "MODELOS_ADJUNTO" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "MODELOS_ADJUNTO" CASCADE;--> statement-breakpoint
ALTER TABLE "GENERACIONES_DOCUMENTO" DROP COLUMN "ID_MODELO";