CREATE TABLE "OPERACIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_HERRAMIENTA" uuid,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
DROP INDEX "PERMISOS_PERFIL_HERRAMIENTA_UNIQUE";--> statement-breakpoint
ALTER TABLE "PERMISOS" ADD COLUMN "ID_OPERACION" uuid;--> statement-breakpoint
ALTER TABLE "OPERACIONES" ADD CONSTRAINT "OPERACIONES_ID_HERRAMIENTA_HERRAMIENTAS_ID_fk" FOREIGN KEY ("ID_HERRAMIENTA") REFERENCES "public"."HERRAMIENTAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "OPERACIONES_HERRAMIENTA_CODIGO_UNIQUE" ON "OPERACIONES" USING btree ("ID_HERRAMIENTA","CODIGO");--> statement-breakpoint
ALTER TABLE "PERMISOS" ADD CONSTRAINT "PERMISOS_ID_OPERACION_OPERACIONES_ID_fk" FOREIGN KEY ("ID_OPERACION") REFERENCES "public"."OPERACIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "PERMISOS_PERFIL_OPERACION_UNIQUE" ON "PERMISOS" USING btree ("ID_PERFIL","ID_OPERACION");