ALTER TABLE "PERMISOS" DROP CONSTRAINT "PERMISOS_ID_HERRAMIENTA_HERRAMIENTAS_ID_fk";
--> statement-breakpoint
ALTER TABLE "PERMISOS" DROP COLUMN "ID_HERRAMIENTA";--> statement-breakpoint
ALTER TABLE "PERMISOS" DROP COLUMN "GESTIONAR";