CREATE TABLE "ARCHIVOS_ADJUNTOS_ENTIDADES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ARCHIVO_ADJUNTO" uuid,
	"ID_ENTIDAD" uuid,
	"ID_REGISTRO" uuid
);
--> statement-breakpoint
ALTER TABLE "LAYOUTS_LEGAJO_SOLAPAS" ADD COLUMN "PARAMETROS" jsonb;--> statement-breakpoint
ALTER TABLE "MENUES_OPCIONES" ADD COLUMN "PARAMETROS" jsonb;--> statement-breakpoint
ALTER TABLE "ARCHIVOS_ADJUNTOS_ENTIDADES" ADD CONSTRAINT "ARCHIVOS_ADJUNTOS_ENTIDADES_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ARCHIVOS_ADJUNTOS_ENTIDADES" ADD CONSTRAINT "ARCHIVOS_ADJUNTOS_ENTIDADES_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ARCHIVOS_ADJUNTOS_ENTIDADES_UNIQUE" ON "ARCHIVOS_ADJUNTOS_ENTIDADES" USING btree ("ID_ARCHIVO_ADJUNTO","ID_ENTIDAD","ID_REGISTRO");