CREATE TABLE "REPORTES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"DESCRIPCION" text,
	"QUERY" text,
	"COLUMNAS" jsonb
);
--> statement-breakpoint
CREATE TABLE "REPORTES_FILTROS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_REPORTE" uuid,
	"ID_FILTRO" uuid,
	"CAMPO" text,
	"ORDEN" integer
);
--> statement-breakpoint
CREATE TABLE "REPORTES_PERFILES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_REPORTE" uuid,
	"ID_PERFIL" uuid
);
--> statement-breakpoint
ALTER TABLE "REPORTES_FILTROS" ADD CONSTRAINT "REPORTES_FILTROS_ID_REPORTE_REPORTES_ID_fk" FOREIGN KEY ("ID_REPORTE") REFERENCES "public"."REPORTES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "REPORTES_FILTROS" ADD CONSTRAINT "REPORTES_FILTROS_ID_FILTRO_FILTROS_ID_fk" FOREIGN KEY ("ID_FILTRO") REFERENCES "public"."FILTROS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "REPORTES_PERFILES" ADD CONSTRAINT "REPORTES_PERFILES_ID_REPORTE_REPORTES_ID_fk" FOREIGN KEY ("ID_REPORTE") REFERENCES "public"."REPORTES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "REPORTES_PERFILES" ADD CONSTRAINT "REPORTES_PERFILES_ID_PERFIL_PERFILES_ID_fk" FOREIGN KEY ("ID_PERFIL") REFERENCES "public"."PERFILES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "REPORTES_CODIGO_UNIQUE" ON "REPORTES" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "REPORTES_PERFILES_REPORTE_PERFIL_UNIQUE" ON "REPORTES_PERFILES" USING btree ("ID_REPORTE","ID_PERFIL");