CREATE TABLE "ACCIONES_EXTERNAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"COMPONENTE" text NOT NULL,
	"PARAMETROS" jsonb,
	"TOKEN" text,
	"TOKEN_EXPIRACION" timestamp with time zone,
	"ACTIVO" boolean DEFAULT true,
	"INMEDIATO" boolean DEFAULT true,
	"REINTENTOS_MAX" integer,
	"REINTENTOS_MARGEN" integer
);
--> statement-breakpoint
CREATE TABLE "ACCIONES_EXTERNAS_COLA" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ACCION_EXTERNA" uuid,
	"FECHA_ENCOLADO" timestamp with time zone DEFAULT now(),
	"RESULTADO" integer,
	"RESULTADO_DESC" text,
	"RESULTADO_FECHA" timestamp with time zone,
	"REINTENTO" integer DEFAULT 0,
	"REINTENTOS_SUPERADOS" boolean DEFAULT false,
	"TIEMPO_CONEXION" integer,
	"ID_ENTIDAD" uuid,
	"ID_REGISTRO" uuid,
	"PARAMETROS" jsonb,
	"REQUEST" jsonb,
	"RESPONSE" jsonb
);
--> statement-breakpoint
CREATE TABLE "COTIZACIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_MONEDA" uuid,
	"COMPRA" double precision,
	"VENTA" double precision,
	"FECHA_CONSULTA" timestamp with time zone,
	"ID_ACCION_EXTERNA_COLA" uuid
);
--> statement-breakpoint
CREATE TABLE "MONEDAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"CODIGO_API" text
);
--> statement-breakpoint
ALTER TABLE "ACCIONES_EXTERNAS_COLA" ADD CONSTRAINT "ACCIONES_EXTERNAS_COLA_ID_ACCION_EXTERNA_ACCIONES_EXTERNAS_ID_fk" FOREIGN KEY ("ID_ACCION_EXTERNA") REFERENCES "public"."ACCIONES_EXTERNAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ACCIONES_EXTERNAS_COLA" ADD CONSTRAINT "ACCIONES_EXTERNAS_COLA_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "COTIZACIONES" ADD CONSTRAINT "COTIZACIONES_ID_MONEDA_MONEDAS_ID_fk" FOREIGN KEY ("ID_MONEDA") REFERENCES "public"."MONEDAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "COTIZACIONES" ADD CONSTRAINT "COTIZACIONES_ID_ACCION_EXTERNA_COLA_ACCIONES_EXTERNAS_COLA_ID_fk" FOREIGN KEY ("ID_ACCION_EXTERNA_COLA") REFERENCES "public"."ACCIONES_EXTERNAS_COLA"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ACCIONES_EXTERNAS_CODIGO_UNIQUE" ON "ACCIONES_EXTERNAS" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "MONEDAS_CODIGO_UNIQUE" ON "MONEDAS" USING btree ("CODIGO");