CREATE TABLE "MENSAJERIA_COLA" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ACCION_EXTERNA" uuid,
	"ID_MENSAJERIA_PLANTILLA" uuid,
	"ID_ENTIDAD" uuid,
	"ID_REGISTRO" uuid,
	"ASUNTO" text,
	"DATOS_RAIZ" jsonb,
	"PLACEHOLDERS" jsonb,
	"RESULTADO" integer,
	"RESULTADO_DESC" text,
	"RESULTADO_FECHA" timestamp with time zone,
	"REINTENTO" integer DEFAULT 0,
	"REINTENTOS_SUPERADOS" boolean DEFAULT false,
	"FECHA_ENCOLADO" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "MENSAJERIA_COLA_ADJUNTOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_MENSAJERIA_COLA" uuid,
	"ID_ARCHIVO_ADJUNTO" uuid
);
--> statement-breakpoint
CREATE TABLE "MENSAJERIA_PLANTILLAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"ID_ARCHIVO_ADJUNTO" uuid,
	"DESCRIPCION" text,
	"ASUNTO" text,
	"COMODIN" jsonb,
	"ID_ESTIMULO_OK" uuid,
	"OBSERVACION_OK" text,
	"ID_ESTIMULO_ERROR" uuid,
	"OBSERVACION_ERROR" text
);
--> statement-breakpoint
ALTER TABLE "MENSAJERIA_COLA" ADD CONSTRAINT "MENSAJERIA_COLA_ID_ACCION_EXTERNA_ACCIONES_EXTERNAS_ID_fk" FOREIGN KEY ("ID_ACCION_EXTERNA") REFERENCES "public"."ACCIONES_EXTERNAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_COLA" ADD CONSTRAINT "MENSAJERIA_COLA_ID_MENSAJERIA_PLANTILLA_MENSAJERIA_PLANTILLAS_ID_fk" FOREIGN KEY ("ID_MENSAJERIA_PLANTILLA") REFERENCES "public"."MENSAJERIA_PLANTILLAS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_COLA" ADD CONSTRAINT "MENSAJERIA_COLA_ID_ENTIDAD_ENTIDADES_ID_fk" FOREIGN KEY ("ID_ENTIDAD") REFERENCES "public"."ENTIDADES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_COLA_ADJUNTOS" ADD CONSTRAINT "MENSAJERIA_COLA_ADJUNTOS_ID_MENSAJERIA_COLA_MENSAJERIA_COLA_ID_fk" FOREIGN KEY ("ID_MENSAJERIA_COLA") REFERENCES "public"."MENSAJERIA_COLA"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_COLA_ADJUNTOS" ADD CONSTRAINT "MENSAJERIA_COLA_ADJUNTOS_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_PLANTILLAS" ADD CONSTRAINT "MENSAJERIA_PLANTILLAS_ID_ARCHIVO_ADJUNTO_ARCHIVOS_ADJUNTOS_ID_fk" FOREIGN KEY ("ID_ARCHIVO_ADJUNTO") REFERENCES "public"."ARCHIVOS_ADJUNTOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_PLANTILLAS" ADD CONSTRAINT "MENSAJERIA_PLANTILLAS_ID_ESTIMULO_OK_ESTIMULOS_ID_fk" FOREIGN KEY ("ID_ESTIMULO_OK") REFERENCES "public"."ESTIMULOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MENSAJERIA_PLANTILLAS" ADD CONSTRAINT "MENSAJERIA_PLANTILLAS_ID_ESTIMULO_ERROR_ESTIMULOS_ID_fk" FOREIGN KEY ("ID_ESTIMULO_ERROR") REFERENCES "public"."ESTIMULOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "MENSAJERIA_PLANTILLAS_CODIGO_UNIQUE" ON "MENSAJERIA_PLANTILLAS" USING btree ("CODIGO");