CREATE TABLE "PROCESOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"DESCRIPCION" text,
	"CRON" text NOT NULL,
	"ACTIVO" boolean DEFAULT true,
	"REINTENTO_MINUTOS" integer,
	"REINTENTOS_MAX" integer
);
--> statement-breakpoint
CREATE TABLE "PROCESOS_EJECUCIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PROCESO" uuid,
	"FECHA_PROGRAMADA" timestamp with time zone NOT NULL,
	"NUMERO_INTENTO" integer DEFAULT 1,
	"ID_EJECUCION_ORIGEN" uuid,
	"ESTADO" text DEFAULT 'pendiente' NOT NULL,
	"FECHA_INICIO" timestamp with time zone,
	"FECHA_INICIO_PASO" timestamp with time zone,
	"FECHA_FIN" timestamp with time zone,
	"ERROR" text,
	"ID_ULTIMO_PASO_OK" uuid,
	"ID_PASO_ERROR" uuid,
	"ID_PASO_DESDE" uuid,
	"ORIGEN" text NOT NULL,
	"ID_USUARIO_DISPARO" uuid
);
--> statement-breakpoint
CREATE TABLE "PROCESOS_EJECUCIONES_PASOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_EJECUCION" uuid,
	"ID_PASO" uuid,
	"FECHA_INICIO" timestamp with time zone NOT NULL,
	"FECHA_FIN" timestamp with time zone,
	"ESTADO" text NOT NULL,
	"ERROR" text
);
--> statement-breakpoint
CREATE TABLE "PROCESOS_PASOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PROCESO" uuid,
	"ORDEN" integer NOT NULL,
	"NOMBRE" text NOT NULL,
	"COMANDO" text NOT NULL,
	"TIMEOUT_MINUTOS" integer
);
--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES" ADD CONSTRAINT "PROCESOS_EJECUCIONES_ID_PROCESO_PROCESOS_ID_fk" FOREIGN KEY ("ID_PROCESO") REFERENCES "public"."PROCESOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES" ADD CONSTRAINT "PROCESOS_EJECUCIONES_ID_EJECUCION_ORIGEN_PROCESOS_EJECUCIONES_ID_fk" FOREIGN KEY ("ID_EJECUCION_ORIGEN") REFERENCES "public"."PROCESOS_EJECUCIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES" ADD CONSTRAINT "PROCESOS_EJECUCIONES_ID_ULTIMO_PASO_OK_PROCESOS_PASOS_ID_fk" FOREIGN KEY ("ID_ULTIMO_PASO_OK") REFERENCES "public"."PROCESOS_PASOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES" ADD CONSTRAINT "PROCESOS_EJECUCIONES_ID_PASO_ERROR_PROCESOS_PASOS_ID_fk" FOREIGN KEY ("ID_PASO_ERROR") REFERENCES "public"."PROCESOS_PASOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES" ADD CONSTRAINT "PROCESOS_EJECUCIONES_ID_PASO_DESDE_PROCESOS_PASOS_ID_fk" FOREIGN KEY ("ID_PASO_DESDE") REFERENCES "public"."PROCESOS_PASOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES" ADD CONSTRAINT "PROCESOS_EJECUCIONES_ID_USUARIO_DISPARO_USUARIOS_ID_fk" FOREIGN KEY ("ID_USUARIO_DISPARO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES_PASOS" ADD CONSTRAINT "PROCESOS_EJECUCIONES_PASOS_ID_EJECUCION_PROCESOS_EJECUCIONES_ID_fk" FOREIGN KEY ("ID_EJECUCION") REFERENCES "public"."PROCESOS_EJECUCIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_EJECUCIONES_PASOS" ADD CONSTRAINT "PROCESOS_EJECUCIONES_PASOS_ID_PASO_PROCESOS_PASOS_ID_fk" FOREIGN KEY ("ID_PASO") REFERENCES "public"."PROCESOS_PASOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROCESOS_PASOS" ADD CONSTRAINT "PROCESOS_PASOS_ID_PROCESO_PROCESOS_ID_fk" FOREIGN KEY ("ID_PROCESO") REFERENCES "public"."PROCESOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "PROCESOS_CODIGO_UNIQUE" ON "PROCESOS" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "PROCESOS_EJECUCIONES_PROCESO_FECHA_UNIQUE" ON "PROCESOS_EJECUCIONES" USING btree ("ID_PROCESO","FECHA_PROGRAMADA");