CREATE TABLE "REPORTES_CATEGORIAS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "MENUES" ADD COLUMN "ORDEN" integer;--> statement-breakpoint
ALTER TABLE "MENUES" ADD COLUMN "ABIERTO" boolean;--> statement-breakpoint
ALTER TABLE "REPORTES" ADD COLUMN "ID_CATEGORIA" uuid;--> statement-breakpoint
CREATE UNIQUE INDEX "REPORTES_CATEGORIAS_CODIGO_UNIQUE" ON "REPORTES_CATEGORIAS" USING btree ("CODIGO");--> statement-breakpoint
ALTER TABLE "REPORTES" ADD CONSTRAINT "REPORTES_ID_CATEGORIA_REPORTES_CATEGORIAS_ID_fk" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "public"."REPORTES_CATEGORIAS"("ID") ON DELETE no action ON UPDATE no action;