CREATE TABLE "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_TIPO_TRAMITE_CAMPO" uuid,
	"ID_ESTADO" uuid
);
--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS" ADD CONSTRAINT "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS_ID_TIPO_TRAMITE_CAMPO_TIPOS_TRAMITE_CAMPOS_ID_fk" FOREIGN KEY ("ID_TIPO_TRAMITE_CAMPO") REFERENCES "public"."TIPOS_TRAMITE_CAMPOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS" ADD CONSTRAINT "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS_ID_ESTADO_ESTADOS_ID_fk" FOREIGN KEY ("ID_ESTADO") REFERENCES "public"."ESTADOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS_CAMPO_ESTADO_UNIQUE" ON "TIPOS_TRAMITE_CAMPOS_OBLIGATORIOS" USING btree ("ID_TIPO_TRAMITE_CAMPO","ID_ESTADO");--> statement-breakpoint
ALTER TABLE "TIPOS_TRAMITE_CAMPOS" DROP COLUMN "OBLIGATORIO";