ALTER TABLE "PRODUCTOS" RENAME TO "CATEGORIAS_PRODUCTOS";--> statement-breakpoint
ALTER TABLE "SUB_PRODUCTOS" RENAME TO "PRODUCTOS";--> statement-breakpoint
ALTER TABLE "PRODUCTOS" RENAME COLUMN "ID_PRODUCTO" TO "ID_CATEGORIA";--> statement-breakpoint
ALTER TABLE "PRODUCTOS" RENAME CONSTRAINT "SUB_PRODUCTOS_ID_PRODUCTO_PRODUCTOS_ID_fk" TO "PRODUCTOS_ID_CATEGORIA_CATEGORIAS_PRODUCTOS_ID_fk";--> statement-breakpoint
ALTER TABLE "CATEGORIAS_PRODUCTOS" ADD COLUMN "SP_PAGO" text;--> statement-breakpoint
ALTER TABLE "CATEGORIAS_PRODUCTOS" ADD COLUMN "SP_ANULAR_PAGO" text;--> statement-breakpoint
ALTER TABLE "PRODUCTOS" ADD COLUMN "ID_MONEDA" uuid;--> statement-breakpoint
ALTER TABLE "PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_ID_MONEDA_MONEDAS_ID_fk" FOREIGN KEY ("ID_MONEDA") REFERENCES "MONEDAS"("ID");--> statement-breakpoint

-- CUENTAS.ID_PRODUCTO apuntaba (por OID, no por nombre) a la vieja PRODUCTOS —
-- ahora renombrada CATEGORIAS_PRODUCTOS. El rename de tabla NO mueve el
-- constraint solo: hay que repuntarlo a mano a la PRODUCTOS nueva (ex SUB_PRODUCTOS).
ALTER TABLE "CUENTAS" DROP CONSTRAINT "CUENTAS_ID_PRODUCTO_PRODUCTOS_ID_fk";--> statement-breakpoint
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_ID_PRODUCTO_PRODUCTOS_ID_fk" FOREIGN KEY ("ID_PRODUCTO") REFERENCES "PRODUCTOS"("ID");--> statement-breakpoint

CREATE TABLE "ENTES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);--> statement-breakpoint
CREATE TABLE "FORMAS_PAGO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);--> statement-breakpoint
CREATE TABLE "FORMAS_DESEMBOLSO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);--> statement-breakpoint
CREATE TABLE "CANALES_PAGO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ENTE" uuid,
	"ID_FORMA_PAGO" uuid
);--> statement-breakpoint
CREATE TABLE "CANALES_DESEMBOLSO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_ENTE" uuid,
	"ID_FORMA_DESEMBOLSO" uuid
);--> statement-breakpoint
CREATE TABLE "PRODUCTOS_CANALES_PAGO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PRODUCTO" uuid,
	"ID_CANAL_PAGO" uuid
);--> statement-breakpoint
CREATE TABLE "PRODUCTOS_CANALES_DESEMBOLSO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_PRODUCTO" uuid,
	"ID_CANAL_DESEMBOLSO" uuid
);--> statement-breakpoint

ALTER TABLE "CANALES_PAGO" ADD CONSTRAINT "CANALES_PAGO_ID_ENTE_ENTES_ID_fk" FOREIGN KEY ("ID_ENTE") REFERENCES "ENTES"("ID");--> statement-breakpoint
ALTER TABLE "CANALES_PAGO" ADD CONSTRAINT "CANALES_PAGO_ID_FORMA_PAGO_FORMAS_PAGO_ID_fk" FOREIGN KEY ("ID_FORMA_PAGO") REFERENCES "FORMAS_PAGO"("ID");--> statement-breakpoint
ALTER TABLE "CANALES_DESEMBOLSO" ADD CONSTRAINT "CANALES_DESEMBOLSO_ID_ENTE_ENTES_ID_fk" FOREIGN KEY ("ID_ENTE") REFERENCES "ENTES"("ID");--> statement-breakpoint
ALTER TABLE "CANALES_DESEMBOLSO" ADD CONSTRAINT "CANALES_DESEMBOLSO_ID_FORMA_DESEMBOLSO_FORMAS_DESEMBOLSO_ID_fk" FOREIGN KEY ("ID_FORMA_DESEMBOLSO") REFERENCES "FORMAS_DESEMBOLSO"("ID");--> statement-breakpoint
ALTER TABLE "PRODUCTOS_CANALES_PAGO" ADD CONSTRAINT "PRODUCTOS_CANALES_PAGO_ID_PRODUCTO_PRODUCTOS_ID_fk" FOREIGN KEY ("ID_PRODUCTO") REFERENCES "PRODUCTOS"("ID");--> statement-breakpoint
ALTER TABLE "PRODUCTOS_CANALES_PAGO" ADD CONSTRAINT "PRODUCTOS_CANALES_PAGO_ID_CANAL_PAGO_CANALES_PAGO_ID_fk" FOREIGN KEY ("ID_CANAL_PAGO") REFERENCES "CANALES_PAGO"("ID");--> statement-breakpoint
ALTER TABLE "PRODUCTOS_CANALES_DESEMBOLSO" ADD CONSTRAINT "PRODUCTOS_CANALES_DESEMBOLSO_ID_PRODUCTO_PRODUCTOS_ID_fk" FOREIGN KEY ("ID_PRODUCTO") REFERENCES "PRODUCTOS"("ID");--> statement-breakpoint
ALTER TABLE "PRODUCTOS_CANALES_DESEMBOLSO" ADD CONSTRAINT "PRODUCTOS_CANALES_DESEMBOLSO_ID_CANAL_DESEMBOLSO_CANALES_DESEMBOLSO_ID_fk" FOREIGN KEY ("ID_CANAL_DESEMBOLSO") REFERENCES "CANALES_DESEMBOLSO"("ID");--> statement-breakpoint

CREATE UNIQUE INDEX "CANALES_PAGO_ENTE_FORMA_UNIQUE" ON "CANALES_PAGO" USING btree ("ID_ENTE","ID_FORMA_PAGO");--> statement-breakpoint
CREATE UNIQUE INDEX "CANALES_DESEMBOLSO_ENTE_FORMA_UNIQUE" ON "CANALES_DESEMBOLSO" USING btree ("ID_ENTE","ID_FORMA_DESEMBOLSO");--> statement-breakpoint
CREATE UNIQUE INDEX "PRODUCTOS_CANALES_PAGO_UNIQUE" ON "PRODUCTOS_CANALES_PAGO" USING btree ("ID_PRODUCTO","ID_CANAL_PAGO");--> statement-breakpoint
CREATE UNIQUE INDEX "PRODUCTOS_CANALES_DESEMBOLSO_UNIQUE" ON "PRODUCTOS_CANALES_DESEMBOLSO" USING btree ("ID_PRODUCTO","ID_CANAL_DESEMBOLSO");
