CREATE TABLE "FERIADOS" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_TIPO_FERIADO" uuid,
	"FECHA" date NOT NULL,
	"DESCRIPCION" text
);
--> statement-breakpoint
CREATE TABLE "TIPOS_FERIADO" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "FERIADOS" ADD CONSTRAINT "FERIADOS_ID_TIPO_FERIADO_TIPOS_FERIADO_ID_fk" FOREIGN KEY ("ID_TIPO_FERIADO") REFERENCES "public"."TIPOS_FERIADO"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "FERIADOS_FECHA_UNIQUE" ON "FERIADOS" USING btree ("FECHA");