CREATE TABLE "IMPORTADORES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CODIGO" text NOT NULL,
	"NOMBRE" text NOT NULL,
	"TABLA_STAGING" text NOT NULL,
	"SP_NOMBRE" text NOT NULL,
	"EXTENSIONES_PERMITIDAS" text NOT NULL,
	"RUTA_DIRECTORIO" text,
	"PATRON_NOMBRE_ARCHIVO" text,
	"TABLA_HISTORICO" text,
	"DIAS_RETENCION_HISTORICO" integer,
	"CARPETA_DESTINO_PROCESADOS" text,
	"DISPARO_AUTOMATICO_ACTIVO" boolean DEFAULT false,
	"MODO_ERROR_AUTOMATICO" text,
	"ACTIVO" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "IMPORTADORES_EJECUCIONES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_IMPORTADOR" uuid NOT NULL,
	"ID_USUARIO_DISPARO" uuid NOT NULL,
	"MODO_ARCHIVO" text NOT NULL,
	"ARCHIVO_NOMBRE" text,
	"ESTADO" text DEFAULT 'pendiente' NOT NULL,
	"RESUMEN_VALIDACION" jsonb,
	"RESUMEN_IMPACTO" jsonb,
	"ERROR" text,
	"ID_ACCION_EXTERNA_COLA" uuid,
	"FECHA_INICIO" timestamp with time zone,
	"FECHA_FIN" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "IMPORTADORES_EJECUCIONES" ADD CONSTRAINT "IMPORTADORES_EJECUCIONES_ID_IMPORTADOR_IMPORTADORES_ID_fk" FOREIGN KEY ("ID_IMPORTADOR") REFERENCES "public"."IMPORTADORES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "IMPORTADORES_EJECUCIONES" ADD CONSTRAINT "IMPORTADORES_EJECUCIONES_ID_USUARIO_DISPARO_USUARIOS_ID_fk" FOREIGN KEY ("ID_USUARIO_DISPARO") REFERENCES "public"."USUARIOS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "IMPORTADORES_EJECUCIONES" ADD CONSTRAINT "IMPORTADORES_EJECUCIONES_ID_ACCION_EXTERNA_COLA_ACCIONES_EXTERNAS_COLA_ID_fk" FOREIGN KEY ("ID_ACCION_EXTERNA_COLA") REFERENCES "public"."ACCIONES_EXTERNAS_COLA"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "IMPORTADORES_CODIGO_UNIQUE" ON "IMPORTADORES" USING btree ("CODIGO");--> statement-breakpoint
CREATE UNIQUE INDEX "IMPORTADORES_EJECUCIONES_ACTIVA_UNIQUE" ON "IMPORTADORES_EJECUCIONES" USING btree ("ID_IMPORTADOR","ID_USUARIO_DISPARO") WHERE "ESTADO" NOT IN ('completado','error','cancelado');