CREATE TABLE "IMPORT_LEGAJOS_CLIENTES_HIST" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_EJECUCION" uuid NOT NULL,
	"NRO_FILA" integer NOT NULL,
	"LEGAJO_NUMERO" text,
	"CLIENTE_TIPO_DOCUMENTO_CODIGO" text,
	"CLIENTE_NRO_DOCUMENTO" text,
	"CLIENTE_ES_TITULAR" text,
	"CLIENTE_CARACTER_CODIGO" text,
	"CLIENTE_APELLIDO" text,
	"CLIENTE_NOMBRE" text,
	"CLIENTE_GENERO_CODIGO" text,
	"CLIENTE_PROVINCIA_CODIGO" text,
	"ESTADO_VALIDACION" text,
	"MENSAJE_VALIDACION" text
);
--> statement-breakpoint
CREATE TABLE "IMPORT_LEGAJOS_CLIENTES_STG" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ID_EJECUCION" uuid NOT NULL,
	"NRO_FILA" integer NOT NULL,
	"LEGAJO_NUMERO" text,
	"CLIENTE_TIPO_DOCUMENTO_CODIGO" text,
	"CLIENTE_NRO_DOCUMENTO" text,
	"CLIENTE_ES_TITULAR" text,
	"CLIENTE_CARACTER_CODIGO" text,
	"CLIENTE_APELLIDO" text,
	"CLIENTE_NOMBRE" text,
	"CLIENTE_GENERO_CODIGO" text,
	"CLIENTE_PROVINCIA_CODIGO" text,
	"ESTADO_VALIDACION" text,
	"MENSAJE_VALIDACION" text
);
--> statement-breakpoint
ALTER TABLE "IMPORT_LEGAJOS_CLIENTES_HIST" ADD CONSTRAINT "IMPORT_LEGAJOS_CLIENTES_HIST_ID_EJECUCION_IMPORTADORES_EJECUCIONES_ID_fk" FOREIGN KEY ("ID_EJECUCION") REFERENCES "public"."IMPORTADORES_EJECUCIONES"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "IMPORT_LEGAJOS_CLIENTES_STG" ADD CONSTRAINT "IMPORT_LEGAJOS_CLIENTES_STG_ID_EJECUCION_IMPORTADORES_EJECUCIONES_ID_fk" FOREIGN KEY ("ID_EJECUCION") REFERENCES "public"."IMPORTADORES_EJECUCIONES"("ID") ON DELETE no action ON UPDATE no action;